#include "trimesh.h"
#include <assert.h>
#include <float.h>
#include <string.h>
#include <algorithm>
#include <cmath>
#include "../ui/TraceUI.h"
extern TraceUI* traceUI;

using namespace std;

Trimesh::~Trimesh()
{
	for (auto m : materials)
		delete m;
	for (auto f : faces)
		delete f;
}

// must add vertices, normals, and materials IN ORDER
void Trimesh::addVertex(const glm::dvec3& v)
{
	vertices.emplace_back(v);
}

void Trimesh::addMaterial(Material* m)
{
	materials.emplace_back(m);
}

void Trimesh::addNormal(const glm::dvec3& n)
{
	normals.emplace_back(n);
}

// Returns false if the vertices a,b,c don't all exist
bool Trimesh::addFace(int a, int b, int c)
{
	int vcnt = vertices.size();

	if (a >= vcnt || b >= vcnt || c >= vcnt)
		return false;

	TrimeshFace* newFace = new TrimeshFace(
	        scene, new Material(*this->material), this, a, b, c);
	newFace->setTransform(this->transform);
	if (!newFace->degen)
		faces.push_back(newFace);
	else
		delete newFace;

	// Don't add faces to the scene's object list so we can cull by bounding
	// box
	return true;
}

// Check to make sure that if we have per-vertex materials or normals
// they are the right number.
const char* Trimesh::doubleCheck()
{
	if (!materials.empty() && materials.size() != vertices.size())
		return "Bad Trimesh: Wrong number of materials.";
	if (!normals.empty() && normals.size() != vertices.size())
		return "Bad Trimesh: Wrong number of normals.";

	return 0;
}

bool Trimesh::intersectLocal(ray& r, isect& i) const
{
	bool have_one = false;
	for (auto face : faces) {
		isect cur;
		if (face->intersectLocal(r, cur)) {
			if (!have_one || (cur.getT() < i.getT())) {
				i = cur;
				have_one = true;
			}
		}
	}
	if (!have_one)
		i.setT(1000.0);
	return have_one;
}

bool TrimeshFace::intersect(ray& r, isect& i) const
{
	return intersectLocal(r, i);
}

// Intersect ray r with the triangle abc.  If it hits returns true,
// and put the parameter in t and the barycentric coordinates of the
// intersection in u (alpha) and v (beta).
bool TrimeshFace::intersectLocal(ray& r, isect& i) const
{
	// YOUR CODE HERE
	//
	// FIXME: Add ray-trimesh intersection
	const TrimeshFace *iFace = this;
	if (glm::dot(iFace->normal,r.getDirection()) == 0)
	 return false;

	glm::dvec3 a_coords = iFace->parent->vertices[iFace->ids[0]];
	glm::dvec3 b_coords = iFace->parent->vertices[iFace->ids[1]];
	glm::dvec3 c_coords = iFace->parent->vertices[iFace->ids[2]];
	glm::dvec3 midPoint = (1.0/3.0) * (a_coords + b_coords + c_coords);
   
	glm::dvec3 area = (glm::cross(a_coords,b_coords) + glm::cross(b_coords,c_coords)
	 + glm::cross(c_coords,a_coords));
	area = glm::normalize(area) * (1.0/2.0);

	// using Point B , C and Midpoint get a subarea
	glm::dvec3 aA = (glm::cross(b_coords,c_coords) 
	+ glm::cross(b_coords,midPoint) + glm::cross(c_coords,midPoint)); 
	aA = glm::normalize(aA) * (1.0/2.0);

	// using Point A , C and Midpoint get b subarea
	glm::dvec3 aB = (glm::cross(a_coords,c_coords) 
	+ glm::cross(a_coords,midPoint) + glm::cross(c_coords,midPoint)); 
	aB = glm::normalize(aB) * (1.0/2.0);

	// using Point A , B and Midpoint get c subarea 
	glm::dvec3 aC = (glm::cross(a_coords,b_coords) 
	+ glm::cross(a_coords,midPoint) + glm::cross(b_coords,midPoint)); 
	aC = glm::normalize(aC) * (1.0/2.0);
     
	glm::dvec3 alpha = aA/area;
	glm::dvec3 beta  = aB/area;
	glm::dvec3 gamma = aC/area; 

	double tIntersect = glm::dot()
	// Check we are hitting the same plane as the triangle
	// check if we are hitting the triangle in that plane
	printf("eee");

	return true;
}

// Once all the verts and faces are loaded, per vertex normals can be
// generated by averaging the normals of the neighboring faces.
void Trimesh::generateNormals()
{
	int cnt = vertices.size();
	normals.resize(cnt);
	std::vector<int> numFaces(cnt, 0);

	for (auto face : faces) {
		glm::dvec3 faceNormal = face->getNormal();

		for (int i = 0; i < 3; ++i) {
			normals[(*face)[i]] += faceNormal;
			++numFaces[(*face)[i]];
		}
	}

	for (int i = 0; i < cnt; ++i) {
		if (numFaces[i])
			normals[i] /= numFaces[i];
	}

	vertNorms = true;
}

